### ISSUE TITLE
it will be better if you can just make each task on seprate file that will make for reader easy to understand and read

### ISSUE THREAD

**Issue by moatasemelsayed** [AhmedWaleedAhmed/Embedded-Linux-Tasks#1]
https://github.com/AhmedWaleedAhmed/Embedded-Linux-Tasks/blob/e3f53e1b0ab74b59ec217b7f1cda7ac27332c435/python/session_1.py#L1

**Comment by AhmedWaleedAhmed** [comment]
@moatasemelsayed addressed in 21cbf19
