### ISSUE TITLE
you will create notes.txt on diffenent places every time according where am I on terminal so please make it fixed path

### ISSUE THREAD

**Issue by moatasemelsayed** [AhmedWaleedAhmed/Embedded-Linux-Tasks#2]
https://github.com/AhmedWaleedAhmed/Embedded-Linux-Tasks/blob/c4e675bd8f392832e940509c53ec46abc43ffef7/challenges/challenge%2301/challenge_01.py#L33C5-L33C8

**Comment by AhmedWaleedAhmed** [comment]
@moatasemelsayed Fixed in de8e126.
